-- TABLES --
DROP TABLE IF EXISTS APPARTENIR;
DROP TABLE IF EXISTS ETRESTYLE;
DROP TABLE IF EXISTS ETRETYPE;
DROP TABLE IF EXISTS ORGANISERACTIVITE;
DROP TABLE IF EXISTS ORGANISERCONCERT;
DROP TABLE IF EXISTS JOUER;
DROP TABLE IF EXISTS RESERVER;
DROP TABLE IF EXISTS FAVORIS;
DROP TABLE IF EXISTS POSSEDE;
DROP TABLE IF EXISTS ARTISTE;
DROP TABLE IF EXISTS ACTIVITE;
DROP TABLE IF EXISTS BILLET;
DROP TABLE IF EXISTS CONCERT;
DROP TABLE IF EXISTS GROUPE;
DROP TABLE IF EXISTS HEBERGEMENT;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS LIEU;
DROP TABLE IF EXISTS SPECTATEUR;
DROP TABLE IF EXISTS STYLE;
DROP TABLE IF EXISTS SOUSSTYLE;
DROP TABLE IF EXISTS TYPE;

-- TRIGGERS --
DROP TRIGGER IF EXISTS gestionAge;
DROP TRIGGER IF EXISTS gestionAgeMinMax;
DROP TRIGGER IF EXISTS gestionPlaces;